### PR TITLE
Run melpazoid on the local repo on CI

### PR DESCRIPTION
**Pull request by akirak**

### CODE REVIEW

**Comment by tecosaur** [comment]
I'm guessing this does something desirable? A little explanation would be good though

**Comment by akirak** [comment]
I've the local repository for melpazoid: https://github.com/riscy/melpazoid#test-a-recipe-for-a-package-on-your-machine

**Comment by akirak** [comment]
`github.workspace` is defined here: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context

**Comment by tecosaur** [comment]
This makes some sense :+1:

**Pull request merged**
