### PR TITLE
Keybinding documentation reference issue #1

### PR DESCRIPTION
**Pull request by WillForan**
brief justification and lots of links to software and guides.
Does internal linking of org docs work on github?

### CODE REVIEW

**Comment by tecosaur** [comment]
Hi Will, thanks for the PR! I think a heading/fuzzy link would probably be safer here. Could you change it to `[[Binding a Shortcut]]` or `[[*Binding a Shortcut][binding a Shortcut]]`?

Other than that, this looks good to merge to me :)

**Comment by tecosaur** [comment]
Oh, one other thing, I'd just do `~emacsclient --eval "(emacs-everywhere)"~` instead of having a code block.

**Comment by tecosaur** [comment]
Thanks, one more request: do you think you could squash your commits and drop the emojis? 😅

**Comment by tecosaur** [comment]
This looks ready to merge, let me know if it's finished and I'll take care of the squashing.

**Comment by WillForan** [comment]
yep! Thanks!

**Pull request merged**
