### PR TITLE
Add Kwin (KDE) Wayland Support

### PR DESCRIPTION
**Pull request by msin32**
Wayland support for kwin based desktops

### CODE REVIEW

**Comment by tecosaur** [comment]
@msin32 many thanks for this! How would you feel if I were to pull your changes, edit them extensively, and push that?

**Comment by msin32** [comment]
> @msin32 many thanks for this! How would you feel if I were to pull your changes, edit them extensively, and push that?

No problem

**Comment by tecosaur** [comment]
Great I'll see how I go :slightly_smiling_face:

**Comment by tecosaur** [comment]
I've just pushed 2f2521769ae90689c5370e7580553f5b1b8f6945, let me know how you find that.

**Pull request closed without merging**
